@echo off
:: -----------------------------------------------------------------------------
:: Tanuki Stories - Launcher (Windows)
:: Installs (if needed), configures, and launches the AI backend + npm server.
:: Also registers itself as a Windows startup application.
:: Usage:  launcher.bat
:: -----------------------------------------------------------------------------
setlocal EnableDelayedExpansion
title Tanuki Stories Launcher

:: Resolve the absolute path of this script so the startup entry is correct
:: even when launched from a shortcut or different working directory.
set "SCRIPT_DIR=%~dp0"
set "SCRIPT_PATH=%~f0"
cd /d "!SCRIPT_DIR!"

:: -- Configurable timeouts (seconds) ------------------------------------------
set BACKEND_WAIT=5
set WEB_SERVER_WAIT=10

:: -- Banner -------------------------------------------------------------------
call :print_banner

:: -- Step 1: Install if not already configured --------------------------------
if not exist ".env.local" (
    echo [Tanuki] No .env.local found -- running installer first...
    echo.
    call install.bat
    if errorlevel 1 (
        echo   X  Installation failed. Please fix any errors and re-run launcher.bat.
        pause
        exit /b 1
    )
    :: Re-check after install
    if not exist ".env.local" (
        echo   X  installer did not produce .env.local -- aborting.
        pause
        exit /b 1
    )
    echo.
    echo   OK  Installation complete. Continuing to launch...
    echo.
)

:: -- Step 2: Register as a startup application --------------------------------
call :register_startup

:: -- Step 3: Launch AI backend (if configured) --------------------------------
call :launch_backend

:: -- Step 4: Launch npm server ------------------------------------------------
call :launch_npm

:: -- Step 5: Open browser -----------------------------------------------------
call :open_browser

echo.
echo --------------------------------------------------------
echo   Tanuki Stories is running!
echo.
echo   App:    http://localhost:3000
echo   Admin:  http://localhost:3000/admin
echo.
echo   Close this window to keep servers running in the background,
echo   or press any key to exit (servers will keep running).
echo --------------------------------------------------------
echo.
pause
goto :eof

:: =============================================================================
:: SUBROUTINES
:: =============================================================================

:print_banner
echo.
echo   ######   ##    ##   ##     ## ##   ## ##  ##
echo      ##   ####   ####  ##   ##  ##  ##  ## ##
echo      ##  ##  ##  ## ## ##  ##   ## ##   ####
echo      ##  ######  ##  ####  ##   ####    ##
echo      ##  ##  ##  ##   ### ##    ## ##   ###
echo      ##  ##  ##  ##    ##  ##   ##  ##  ## ##
echo.
echo   Tanuki Stories -- Launcher (Windows)
echo   --------------------------------------------------------
echo.
goto :eof

:: -----------------------------------------------------------------------------
:register_startup
echo [Tanuki] Registering as a startup application...
:: Check if an identical entry already exists before writing
for /f "tokens=2*" %%a in ('reg query "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" /v "TanukiStories" 2^>nul ^| findstr /i "TanukiStories"') do set "EXISTING_ENTRY=%%b"
if "!EXISTING_ENTRY!"=="\"!SCRIPT_PATH!\"" (
    echo   OK  Startup entry already up to date
) else (
    reg add "HKCU\Software\Microsoft\Windows\CurrentVersion\Run" ^
        /v "TanukiStories" ^
        /t REG_SZ ^
        /d "\"!SCRIPT_PATH!\"" ^
        /f >nul 2>&1
    if errorlevel 1 (
        echo   Warning: Could not register startup entry ^(non-fatal^).
    ) else (
        echo   OK  Registered in HKCU Run key
    )
)
echo.
goto :eof

:: -----------------------------------------------------------------------------
:launch_backend
:: Check which AI backend scripts exist (generated by install.bat)
if exist "start-vllm.bat" (
    echo [Tanuki] Starting vLLM inference server in a new window...
    start "Tanuki - vLLM Server" cmd /k "cd /d \"!SCRIPT_DIR!\" && call start-vllm.bat"
    echo   OK  vLLM server window launched
    echo   Waiting !BACKEND_WAIT! seconds for the server to initialize...
    timeout /t !BACKEND_WAIT! /nobreak >nul
) else if exist "start-llamacpp.bat" (
    echo [Tanuki] Starting llama.cpp inference server in a new window...
    start "Tanuki - llama.cpp Server" cmd /k "cd /d \"!SCRIPT_DIR!\" && call start-llamacpp.bat"
    echo   OK  llama.cpp server window launched
    echo   Waiting !BACKEND_WAIT! seconds for the server to initialize...
    timeout /t !BACKEND_WAIT! /nobreak >nul
) else (
    echo [Tanuki] No local AI backend script found -- skipping ^(external API or mock mode^).
)
echo.
goto :eof

:: -----------------------------------------------------------------------------
:launch_npm
:: Use the production server if a Next.js build exists, otherwise dev server.
echo [Tanuki] Starting npm server in a new window...
if exist ".next\BUILD_ID" (
    echo   Using production build ^(npm start^)...
    start "Tanuki - Web Server" cmd /k "cd /d \"!SCRIPT_DIR!\" && npm start"
) else (
    echo   No production build found -- using development server ^(npm run dev^)...
    echo   Tip: run "npm run build" once for faster production startup.
    start "Tanuki - Web Server" cmd /k "cd /d \"!SCRIPT_DIR!\" && npm run dev"
)
echo   OK  Web server window launched
echo.
goto :eof

:: -----------------------------------------------------------------------------
:open_browser
:: Give the dev/prod server a moment to bind before opening the browser.
echo [Tanuki] Waiting for web server to start ^(!WEB_SERVER_WAIT! seconds^)...
timeout /t !WEB_SERVER_WAIT! /nobreak >nul
echo [Tanuki] Opening http://localhost:3000 in the default browser...
start "" "http://localhost:3000"
echo   OK  Browser opened
echo.
goto :eof
